%import common.INT
%import common.FLOAT
%import common.CNAME -> NAME // This is a standard and robust definition for NAME
%import common.WS
%import common.C_COMMENT

// --- Ignoring ---
%ignore WS          // Ignore whitespace (spaces, tabs, and newlines!)
%ignore C_COMMENT   // Also ignore C-style comments (/* ... */)
?start: statement*

?statement: simple_statement ";"
          | block_statement

?simple_statement: definition
                 | expression
                 | return

?block_statement: function_def

return: "return" expression

?expression: expression "+" term   -> add
    | expression "-" term   -> sub
    | term

?term : term "*" factor   -> mul
    | term "/" factor   -> div
    | factor

?factor: num_atom

?block: "{" statement* "}"

?dimensions: "<" INT ("," INT)* ">" -> dimensions

?definition: "var" NAME "=" expression  -> var_def
    | "var" NAME dimensions "=" expression  -> array_def


?function_def: "def" NAME "(" [NAME ("," NAME)*] ")" block

?num_atom: atom
    | "-" num_atom       -> neg
    | "+" num_atom       -> pos
    | call -> call_expr
    | "(" expression ")"
    | NAME

?call: NAME "(" [expression ("," expression)*] ")"

?list: "[" expression ("," expression)*  "]"

?atom: FLOAT
    | INT
    | NAME
    | list
